1: 2
2: 1 3
3: 2 4 29
4: 3 5 27 28
5: 4 6 8 23 27
6: 5 7
7: 6
8: 5 23 22 20 9
9: 8 20 10 14
10: 9 13 11
11: 12 10
12: 11 13 50
13: 12 10 14
14: 13 9 20 15
15: 14 19 16 17
16: 15 17
17: 15 16 18
18: 19 17
19: 20 15 18
20: 8 9 14 19
21: 22 20 8
22: 21 8 23
23: 22 24 5 27
24: 23 25 26
25: 24 26
26: 24 25 27
27: 28 23
28: 4 27 29
29: 3 28 30
30: 29 31
31: 30
32: 17 33
33: 32 34 35 38
34: 33 35
35: 36 33 34
36: 35 37
37: 36 38 39 44
38: 36 37 39 33
39: 37 38 40
40: 39 41
41: 40 49 42
42: 43 41 49
43: 42 44 54
44: 46 45 43 37
45: 46 44
46: 45 44 47
47: 46
49: 42 41 50 51
50: 49 54 51
51: 50 49 42 54 53 52
52: 51
53: 54 51
54: 53 43 42